# Form implementation generated from reading ui file '/home/adhdfurro/Dokumenty/pluscord/pluscord/qt/error_notadded.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ErrorNotAdded(object):
    def setupUi(self, ErrorNotAdded):
        ErrorNotAdded.setObjectName("ErrorNotAdded")
        ErrorNotAdded.resize(480, 160)
        self.ExitErrorNotAdded = QtWidgets.QDialogButtonBox(parent=ErrorNotAdded)
        self.ExitErrorNotAdded.setGeometry(QtCore.QRect(10, 120, 461, 32))
        self.ExitErrorNotAdded.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ExitErrorNotAdded.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ExitErrorNotAdded.setCenterButtons(True)
        self.ExitErrorNotAdded.setObjectName("ExitErrorNotAdded")
        self.LableErrorNotAdded = QtWidgets.QLabel(parent=ErrorNotAdded)
        self.LableErrorNotAdded.setGeometry(QtCore.QRect(10, 10, 461, 101))
        self.LableErrorNotAdded.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.LableErrorNotAdded.setObjectName("LableErrorNotAdded")

        self.retranslateUi(ErrorNotAdded)
        self.ExitErrorNotAdded.accepted.connect(ErrorNotAdded.accept) # type: ignore
        self.ExitErrorNotAdded.rejected.connect(ErrorNotAdded.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ErrorNotAdded)

    def retranslateUi(self, ErrorNotAdded):
        _translate = QtCore.QCoreApplication.translate
        ErrorNotAdded.setWindowTitle(_translate("ErrorNotAdded", "Error"))
        self.LableErrorNotAdded.setText(_translate("ErrorNotAdded", "Sorry! This feature wasnt added yet :<"))
