# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QCommandLinkButton, QFrame,
    QGraphicsView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QScrollArea, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(801, 600)
        self.Add_servers = QAction(MainWindow)
        self.Add_servers.setObjectName(u"Add_servers")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionPlaceholder_Channel = QAction(MainWindow)
        self.actionPlaceholder_Channel.setObjectName(u"actionPlaceholder_Channel")
        self.actionLeave_Server = QAction(MainWindow)
        self.actionLeave_Server.setObjectName(u"actionLeave_Server")
        self.actionOpen_Console = QAction(MainWindow)
        self.actionOpen_Console.setObjectName(u"actionOpen_Console")
        self.actionOpen_Console.setCheckable(False)
        self.actionAdd_Fake_User = QAction(MainWindow)
        self.actionAdd_Fake_User.setObjectName(u"actionAdd_Fake_User")
        self.actionAdd_Fake_Server = QAction(MainWindow)
        self.actionAdd_Fake_Server.setObjectName(u"actionAdd_Fake_Server")
        self.actionSend_Test_Message = QAction(MainWindow)
        self.actionSend_Test_Message.setObjectName(u"actionSend_Test_Message")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.ChatInput = QFrame(self.centralwidget)
        self.ChatInput.setObjectName(u"ChatInput")
        self.ChatInput.setGeometry(QRect(0, 510, 651, 41))
        self.ChatInput.setFrameShape(QFrame.Shape.StyledPanel)
        self.ChatInput.setFrameShadow(QFrame.Shadow.Raised)
        self.ChatTextInput = QLineEdit(self.ChatInput)
        self.ChatTextInput.setObjectName(u"ChatTextInput")
        self.ChatTextInput.setGeometry(QRect(90, 0, 521, 41))
        self.ChatAddEmoji = QPushButton(self.ChatInput)
        self.ChatAddEmoji.setObjectName(u"ChatAddEmoji")
        self.ChatAddEmoji.setGeometry(QRect(50, 0, 41, 41))
        self.ChatSendText = QCommandLinkButton(self.ChatInput)
        self.ChatSendText.setObjectName(u"ChatSendText")
        self.ChatSendText.setGeometry(QRect(610, 0, 41, 41))
        self.ChatSendText.setIconSize(QSize(30, 30))
        self.ChatAddFile = QPushButton(self.ChatInput)
        self.ChatAddFile.setObjectName(u"ChatAddFile")
        self.ChatAddFile.setGeometry(QRect(0, 0, 41, 41))
        self.ChatOutputView = QScrollArea(self.centralwidget)
        self.ChatOutputView.setObjectName(u"ChatOutputView")
        self.ChatOutputView.setGeometry(QRect(0, -20, 651, 521))
        self.ChatOutputView.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.ChatOutputView.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 649, 519))
        self.ChatTextView = QPlainTextEdit(self.scrollAreaWidgetContents)
        self.ChatTextView.setObjectName(u"ChatTextView")
        self.ChatTextView.setGeometry(QRect(-7, 19, 661, 501))
        self.ChatTextView.setReadOnly(True)
        self.ChatOutputView.setWidget(self.scrollAreaWidgetContents)
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(660, 0, 141, 551))
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.UserViewScroll = QScrollArea(self.frame)
        self.UserViewScroll.setObjectName(u"UserViewScroll")
        self.UserViewScroll.setGeometry(QRect(0, 0, 141, 551))
        self.UserViewScroll.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 139, 549))
        self.UserListWidget = QWidget(self.scrollAreaWidgetContents_3)
        self.UserListWidget.setObjectName(u"UserListWidget")
        self.UserListWidget.setGeometry(QRect(-1, -1, 141, 551))
        self.UserViewData = QWidget(self.UserListWidget)
        self.UserViewData.setObjectName(u"UserViewData")
        self.UserViewData.setGeometry(QRect(0, 0, 141, 51))
        self.UserName = QLabel(self.UserViewData)
        self.UserName.setObjectName(u"UserName")
        self.UserName.setGeometry(QRect(50, 10, 81, 20))
        self.UserProfileIcon = QGraphicsView(self.UserViewData)
        self.UserProfileIcon.setObjectName(u"UserProfileIcon")
        self.UserProfileIcon.setGeometry(QRect(10, 10, 31, 31))
        self.UserStatus = QLabel(self.UserViewData)
        self.UserStatus.setObjectName(u"UserStatus")
        self.UserStatus.setGeometry(QRect(50, 30, 81, 19))
        self.UserViewScroll.setWidget(self.scrollAreaWidgetContents_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.MainMenuBar = QMenuBar(MainWindow)
        self.MainMenuBar.setObjectName(u"MainMenuBar")
        self.MainMenuBar.setGeometry(QRect(0, 0, 801, 25))
        self.MainMenuBar.setNativeMenuBar(True)
        self.MenuServers = QMenu(self.MainMenuBar)
        self.MenuServers.setObjectName(u"MenuServers")
        self.menuPlaceholder_01 = QMenu(self.MenuServers)
        self.menuPlaceholder_01.setObjectName(u"menuPlaceholder_01")
        self.menuSettings = QMenu(self.MainMenuBar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuDebug = QMenu(self.MainMenuBar)
        self.menuDebug.setObjectName(u"menuDebug")
        self.menuDebug.setEnabled(True)
        MainWindow.setMenuBar(self.MainMenuBar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.MainMenuBar.addAction(self.MenuServers.menuAction())
        self.MainMenuBar.addAction(self.menuSettings.menuAction())
        self.MainMenuBar.addAction(self.menuDebug.menuAction())
        self.MenuServers.addAction(self.Add_servers)
        self.MenuServers.addSeparator()
        self.MenuServers.addAction(self.menuPlaceholder_01.menuAction())
        self.menuPlaceholder_01.addAction(self.actionPlaceholder_Channel)
        self.menuPlaceholder_01.addSeparator()
        self.menuPlaceholder_01.addAction(self.actionLeave_Server)
        self.menuSettings.addAction(self.actionAbout)
        self.menuDebug.addAction(self.actionOpen_Console)
        self.menuDebug.addSeparator()
        self.menuDebug.addAction(self.actionAdd_Fake_User)
        self.menuDebug.addAction(self.actionAdd_Fake_Server)
        self.menuDebug.addAction(self.actionSend_Test_Message)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Pluscord - (Server_Name, Channel_Name)", None))
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(QCoreApplication.translate("MainWindow", u"Pluscord - (Server_Name, Channel_Name)", None))
#endif // QT_CONFIG(whatsthis)
        self.Add_servers.setText(QCoreApplication.translate("MainWindow", u"Add servers..", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionPlaceholder_Channel.setText(QCoreApplication.translate("MainWindow", u"Placeholder Channel", None))
        self.actionLeave_Server.setText(QCoreApplication.translate("MainWindow", u"Leave Server", None))
        self.actionOpen_Console.setText(QCoreApplication.translate("MainWindow", u"Open Console", None))
        self.actionAdd_Fake_User.setText(QCoreApplication.translate("MainWindow", u"Add Fake User", None))
        self.actionAdd_Fake_Server.setText(QCoreApplication.translate("MainWindow", u"Add Fake Server", None))
        self.actionSend_Test_Message.setText(QCoreApplication.translate("MainWindow", u"Send Test Message", None))
        self.ChatTextInput.setText("")
        self.ChatTextInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Send a message into (Channel_Name)...", None))
#if QT_CONFIG(whatsthis)
        self.ChatAddEmoji.setWhatsThis(QCoreApplication.translate("MainWindow", u"Add an emoji into your message..", None))
#endif // QT_CONFIG(whatsthis)
        self.ChatAddEmoji.setText(QCoreApplication.translate("MainWindow", u"Emoji", None))
#if QT_CONFIG(whatsthis)
        self.ChatSendText.setWhatsThis(QCoreApplication.translate("MainWindow", u"Send a message into (Channel_Name)...", None))
#endif // QT_CONFIG(whatsthis)
        self.ChatSendText.setText("")
#if QT_CONFIG(whatsthis)
        self.ChatAddFile.setWhatsThis(QCoreApplication.translate("MainWindow", u"Add a File into your message..", None))
#endif // QT_CONFIG(whatsthis)
        self.ChatAddFile.setText(QCoreApplication.translate("MainWindow", u"File", None))
#if QT_CONFIG(whatsthis)
        self.ChatOutputView.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.UserName.setText(QCoreApplication.translate("MainWindow", u"Placeholder", None))
        self.UserStatus.setText(QCoreApplication.translate("MainWindow", u"Placeholder", None))
        self.MenuServers.setTitle(QCoreApplication.translate("MainWindow", u"Servers", None))
        self.menuPlaceholder_01.setTitle(QCoreApplication.translate("MainWindow", u"Placeholder 01", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuDebug.setTitle(QCoreApplication.translate("MainWindow", u"Debug", None))
#if QT_CONFIG(whatsthis)
        self.statusbar.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

