# Form implementation generated from reading ui file '/home/adhdfurro/Dokumenty/pluscord/pluscord/qt/startwarning.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Warning(object):
    def setupUi(self, Warning):
        Warning.setObjectName("Warning")
        Warning.resize(400, 300)
        Warning.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        Warning.setAutoFillBackground(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Warning)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.UpperText = QtWidgets.QPlainTextEdit(parent=Warning)
        self.UpperText.setGeometry(QtCore.QRect(100, 20, 201, 31))
        font = QtGui.QFont()
        font.setFamily("System-ui")
        font.setPointSize(14)
        font.setBold(False)
        self.UpperText.setFont(font)
        self.UpperText.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.UpperText.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.UpperText.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.UpperText.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.UpperText.setLineWrapMode(QtWidgets.QPlainTextEdit.LineWrapMode.WidgetWidth)
        self.UpperText.setReadOnly(True)
        self.UpperText.setObjectName("UpperText")
        self.MIdText = QtWidgets.QPlainTextEdit(parent=Warning)
        self.MIdText.setGeometry(QtCore.QRect(13, 69, 371, 171))
        self.MIdText.setReadOnly(True)
        self.MIdText.setObjectName("MIdText")

        self.retranslateUi(Warning)
        self.buttonBox.accepted.connect(Warning.accept) # type: ignore
        self.buttonBox.rejected.connect(Warning.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Warning)

    def retranslateUi(self, Warning):
        _translate = QtCore.QCoreApplication.translate
        Warning.setWindowTitle(_translate("Warning", "Warning"))
        Warning.setWhatsThis(_translate("Warning", "Pluscord (REFERENCE ONLY)"))
        self.UpperText.setWhatsThis(_translate("Warning", "<html><head/><body><p>Welcome to Pluscord!</p></body></html>"))
        self.UpperText.setPlainText(_translate("Warning", "Welcome to Pluscord!"))
        self.MIdText.setPlainText(_translate("Warning", "This application is completly still in the works. Nothing at all is probably going to be working yet. This window youre seeing right now is an example of how the product will be shaped and stuffs. -w-\n"
"\n"
"Thanks ^w^ - ADHDFurro\n"
"\n"
"Pluscord Team (2024)"))
